services:
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    networks:
      - backend
    volumes:
      - kafka-data:/var/lib/kafka/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

  discovery-server:
    image: 'discovery-server:latest'
    container_name:
      'discovery-server-container'
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

  api-gateway:
    image: 'api-gateway:latest'
    container_name:
      'api-gateway-container'
    environment:
      - JWT_KEY=${JWT_KEY}
      - EUREKA_URI=http://discovery-server:8761/eureka
    networks:
      - backend
    ports:
      - "80:80"
    depends_on:
      - discovery-server
    restart: unless-stopped
    healthcheck:
      test: "curl --fail --silent localhost:80/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

  order-service:
    image: 'order-service:latest'
    container_name: 'order-service-container'
    depends_on:
      - order-db
      - discovery-server
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/${DB_ORDER_SCHEMA}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - EUREKA_URI=http://discovery-server:8761/eureka
      - KAFKA_BOOTSTRAP=kafka:9092
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: "curl --fail --silent localhost:80/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

  order-db:
    image: postgres
    container_name: 'order-db'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_ORDER_SCHEMA}
    networks:
      - backend
    volumes:
      - order-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "${DB_ORDER_SCHEMA}" ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

  auth-service:
    image: 'auth-service:latest'
    container_name:
      'auth-service-container'
    depends_on:
      - auth-db
      - discovery-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/${DB_AUTH_SCHEMA}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_KEY=${JWT_KEY}
      - EUREKA_URI=http://discovery-server:8761/eureka
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: "curl --fail --silent localhost:80/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

  auth-db:
    image: postgres
    container_name: 'auth-db'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_AUTH_SCHEMA}
    networks:
      - backend
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "${DB_AUTH_SCHEMA}" ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

  user-service:
    image: 'user-service:latest'
    container_name: 'user-service-container'
    depends_on:
      - user-db
      - user-redis-cache
      - discovery-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/${DB_USER_SCHEMA}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_HOST=user-redis-cache
      - EUREKA_URI=http://discovery-server:8761/eureka
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

  user-db:
    image: postgres
    container_name: user-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_USER_SCHEMA}
    networks:
      - backend
    volumes:
      - user-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "${DB_USER_SCHEMA}" ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

  user-redis-cache:
    image: 'redis:alpine'
    container_name: 'redis-cache'
    networks:
      - backend
    volumes:
      - user-redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

  payment-service:
    image: 'payment-service:latest'
    container_name: 'payment-service-container'
    depends_on:
      - discovery-server
      - kafka
      - payment-db
    environment:
      - EUREKA_URI=http://discovery-server:8761/eureka
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}
      - MONGO_HOST=payment-db
      - MONGO_DB_URI=${MONGO_DB_URI}
      - KAFKA_BOOTSTRAP=kafka:9092
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: "curl --fail --silent localhost:80/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

  payment-db:
    image: mongo
    container_name: payment-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    networks:
      - backend
    volumes:
      - payment-db-data:/data/db
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  user-db-data:
  user-redis-data:
  auth-db-data:
  order-db-data:
  payment-db-data:
  kafka-data:

networks:
  backend:
    driver: bridge