spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin

      database: ${MONGO_DB}
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}

  liquibase:
    url: mongodb://localhost:27017/${MONGO_DB}?authSource=admin

external-api:
  random-number:
    host: https://www.random.org
    url: /integers?num=1&format=plain&min=0&max=100000&col=1&base=10