spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin

      database: ${MONGO_DB}
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}

  liquibase:
    url: mongodb://localhost:27017/${MONGO_DB}?authSource=admin

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG