spring:
  application:
    name: "payment-service"

  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: 27017
      authentication-database: admin

      database: ${MONGO_DB}
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: ${MONGO_DB_URI:mongodb://localhost:27017/${MONGO_DB}?authSource=admin}
    driver-class-name: liquibase.ext.mongodb.database.MongoClientDriver

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP}
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.add.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  cloud:
    discovery:
      enabled: false
    loadbalancer:
      enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: jurabrezgunov@gmail.com
    properties:
      mail:
        debug: true
        smtp:
          auth:
            mechanisms: XOAUTH2
          starttls:
            enable: true
            required: true
    gmail:
      client-id: ${GCP_CLIENT_ID}
      client-secret: ${GCP_CLIENT_SECRET}
      refresh-token: ${GMAIL_REFRESH_TOKEN}

server:
  port: 80

eureka:
  client:
    webclient:
      enabled: false

services:
  user-service:
    url: ${USER_SERVICE_URL:}

external-api:
  random-number:
    host: https://www.random.org
    url: /integers?num=1&format=plain&min=0&max=100000&col=1&base=10
